package com.artech.prototype2.saver.entity;
// Generated 10.12.2014 0:49:32 by Hibernate Tools 3.6.0



/**
 * BigramEnVarOne generated by hbm2java
 */
public class BigramEnVarOne  implements java.io.Serializable, Entity {


     private Integer enid;
     private String wordOne;
     private String wordTwo;
     private int count;

    public BigramEnVarOne() {
    }

    public BigramEnVarOne(String wordOne, String wordTwo, int count) {
       this.wordOne = wordOne;
       this.wordTwo = wordTwo;
       this.count = count;
    }
   
    public Integer getEnid() {
        return this.enid;
    }
    
    public void setEnid(Integer enid) {
        this.enid = enid;
    }
    public String getWordOne() {
        return this.wordOne;
    }
    
    public void setWordOne(String wordOne) {
        this.wordOne = wordOne;
    }
    public String getWordTwo() {
        return this.wordTwo;
    }
    
    public void setWordTwo(String wordTwo) {
        this.wordTwo = wordTwo;
    }
    public int getCount() {
        return this.count;
    }
    
    public void setCount(int count) {
        this.count = count;
    }




}


