package com.artech.prototype2.saver.entity;
// Generated 10.12.2014 0:49:32 by Hibernate Tools 3.6.0



/**
 * DictionaryRu generated by hbm2java
 */
public class DictionaryRu  implements java.io.Serializable, Entity {


     private Integer ruid;
     private String word;
     private int count;

    public DictionaryRu() {
    }

    public DictionaryRu(String word, int count) {
       this.word = word;
       this.count = count;
    }
   
    public Integer getRuid() {
        return this.ruid;
    }
    
    public void setRuid(Integer ruid) {
        this.ruid = ruid;
    }
    public String getWord() {
        return this.word;
    }
    
    public void setWord(String word) {
        this.word = word;
    }
    public int getCount() {
        return this.count;
    }
    
    public void setCount(int count) {
        this.count = count;
    }




}


