/*Создание таблицы индексов для англоязычных слов*/
CREATE TABLE IF NOT EXISTS INDEXES_EN(
    INDEXID INT(20) NOT NULL auto_increment,
    ENID INT(20) NOT NULL,
    DOCID INT(20) NOT NULL,
    POSIT INT(20) NOT NULL,
    TF FLOAT(20) NOT NULL,
    TFIDF FLOAT(20) NOT NULL,
    PRIMARY KEY(INDEXID),
    CONSTRAINT FOREIGN KEY (ENID) REFERENCES DICTIONARY_EN (ENID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FOREIGN KEY (DOCID) REFERENCES DOCUMENTS_EN (DOCID) ON DELETE CASCADE ON UPDATE CASCADE
);