/*Создание таблицы индексов для русскоязычных слов*/
CREATE TABLE IF NOT EXISTS INDEXES_RU(
    INDEXID INT(20) NOT NULL auto_increment,
    RUID INT(20) NOT NULL,
    DOCID INT(20) NOT NULL,
    POSIT INT(20) NOT NULL,
    TF FLOAT(20) NOT NULL,
    TFIDF FLOAT(20) NOT NULL,
    PRIMARY KEY(INDEXID),
    CONSTRAINT FOREIGN KEY (RUID) REFERENCES DICTIONARY_RU (RUID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FOREIGN KEY (DOCID) REFERENCES DOCUMENTS_RU (DOCID) ON DELETE CASCADE ON UPDATE CASCADE
);