CREATE TABLE IF NOT EXISTS THREEGRAM_EN_VAR_TWO (
	ENID INT(20) NOT NULL auto_increment,
    WORD_ONE VARCHAR(200) NOT NULL,
    WORD_TWO VARCHAR(200) NOT NULL,
    WORD_THREE VARCHAR(200) NOT NULL,
    COUNT INT(20) NOT NULL,
    PRIMARY KEY (ENID)
);
